### ISSUE TITLE
Add Episode from x,y,z

### ISSUE THREAD

**Issue by nootsponge** [ContactsPlusLive/contactsplus.live#1]
a
# something random3

.createEpisode s4e100
```yaml
---
season: 4
episode: 100
title: Dementia, Pineapple on Pizza, and Headless Lounge Love??
description: In this episode, some returning guests and our resident blue wolf play some old and brand new games around the classic "Whose Line Is It Anyway?" format.
format: whoseLine
airDate: 2024-05-25
duration: "02:03:17"
ytID: 1qqVYa4d9Wg
tags:
  - game show
crew:
  - name: Wolf Seisenbacher
    role: host
  - name: GlitchFlux
    role: cohost
  - name: NootSponge
    role: producer
  - name: Matorin Talfax
    role: cameraSwitcher
  - name: RaspberryKitty1
    role: cohost
guests:
  - Defhammer
  - Namogod
  - SlyTheFloof
  - Cloud_striker
  - Cerealbowl
  - Beethoven
```
awdawd
