### ISSUE TITLE
Create new episode S4E50

### ISSUE THREAD

**Issue by nootsponge** [ContactsPlusLive/contactsplus.live#3]
# Season 4 Episode 50

.createEpisode s4e50
```yaml
---
season: 4
episode: 50
title: Captain Wolf of the SS SALTINES!! Guns of Icarus with the CPlus Community!
description: Wolf and Matorin host some Guns of Icarus, captaining steampunk airships against each other! Pretty cool if I do say so myself. Even some rando's joined in!
format: community
airDate: 2024-05-02
duration: "1:56:44"
ytID: BuPwpXTFabk
tags:
  - community night
  - guns of icarus
  - gaming
crew:
  - name: Wolf Seisenbacher
    role: host
  - name: Matorin Talfax
    role: cohost
guests:
  - DevPixel
  - VoidTheProtogen
  - Mizuhiro Neko
```
